In [1]:
import numpy as np


In [3]:
#linear algebra really good for machine learning.  Linear Regression.  
#Cutting Deep Learning is also Linear algebra

SyntaxError: invalid syntax (<ipython-input-3-2a9ce781b09d>, line 2)

In [4]:
#vector is an ordered sequence of numbers

In [5]:
u = np.array([1,3,7])

In [6]:
u

array([1, 3, 7])

In [8]:
#adding two lists.  concatanates:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [9]:
#adding up the arrays does the math
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [12]:
#m x n Matrix - rectangular array of numbers with m rows and n columns.  the entry in the ith row and jth column .  aij
#numpy builds matrix via a list of lists

m = np.array([[1,3,7],[4,6,3],[2,5,6]])

In [13]:
m

array([[1, 3, 7],
       [4, 6, 3],
       [2, 5, 6]])

In [14]:
v = np.array([1,3,7])
w = np.array([1,0,1])
print(v+w)
print(v-w)

[2 3 8]
[0 3 6]


In [17]:
a = np.array([[1,2,6],[4,8,3],[9,2,1]])
b = np.array([[9,7,3],[6,8,2],[4,2,4]])
print(a+b)
print(a-b)

[[10  9  9]
 [10 16  5]
 [13  4  5]]
[[-8 -5  3]
 [-2  0  1]
 [ 5  0 -3]]


In [18]:
2*np.array([1,3,7])

array([ 2,  6, 14])

In [19]:
3*np.array([[1,2,6],[4,8,3],[9,2,1]])

array([[ 3,  6, 18],
       [12, 24,  9],
       [27,  6,  3]])

In [20]:
#Dot Product
#Vectors as arrows in space.  bit arrows pointing in the same directions
#gives a big dot product



In [25]:
#dot product uses @ sign
#girl scout cookie of (1 girl sells 5, 3 girls sell 4, 7 girls sell 2 each)

v = np.array([1,3,7])
w = np.array([5,4,2])

v @ w

31

In [26]:
#old school method.  'dot dot method
v.dot(w)

31

In [29]:
#matrix multiplication.  dot product of row x columns
#2x3 x 3x2 = 2x2

In [30]:
np.array([4,5,6]) @ np.array([8,10,12])

154

In [36]:
# city 1, city 2, cookies, muffins matrix
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])
print(a@b)

[[ 58  64]
 [139 154]]


In [37]:
# useful example:  aggregate in each city, how many of each product were sold in each city

In [38]:
a = np.array([[1,2],[4,8]])
b = np.array([[2,9],[3,6]])
print(a@b)

[[ 8 21]
 [32 84]]


In [40]:
#Vector Norm.  dot product of a vector with itself just reflects how big that vector is
#sq root of that number is the length of the arrow.
#this value is often called the vector's norm or 'magnitude'
x = np.array([3,4])
np.linalg.norm(x)

5.0

In [41]:
#scikitlearn